// <auto-generated />
namespace Health_Insurance_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class role_v6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(role_v6));
        
        string IMigrationMetadata.Id
        {
            get { return "202109040639252_role_v6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
